### PR TITLE
Enforce strict datetime parsing

### LINKED ISSUE #213: [PE-D] undocumented behavior in iadd command
iadd r/01-123 d/FLOOR BROKEN t/2022/2/30 9:05PM

When the above invalid date (Feb 30) was added, it was rounded to Feb 28 when input, but this rounding correction behavior is not documented in the UG.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nickyfoo/ped#15

### PR DESCRIPTION
**Pull request by stein414**
## What this does
Closes #213 by changing from default `ResolverStyle.Smart` to `Strict`

## How to test
1. run `iadd r/01-234 d/Something exploded t/2020/2/30 12:00am`, it should fail and show the constraints message
2. run `iadd r/01-234 d/Something exploded t/2020/2/29 12:00am`, it should work

### CODE REVIEW

**Review by benedictkhoomw — CHANGES_REQUESTED** [review]
Thank you for fixing the date rounding issue.

However, dates outside the specified format are still accepted. For example `iadd r/01-234 d/Something exploded t/2021/000001/1 12:00am` is still accepted.

**Comment by stein414** [comment]
I decided to just allow that and provide that in the help command. Will update the documentation later.
image

**Review by benedictkhoomw — COMMENTED** [review]
Hmm, the left padding of 0's also seems to work for the hour of the time:

`iadd r/01-234 d/Something exploded t/2021/000001/000000001 000012:01aM`

**Comment by stein414** [comment]
Hmm, if that is the case, then I think narrowing the valid formats would be better. i.e. MM dd hh (enforce double digits always)

**Comment by benedictkhoomw** [comment]
> 
> 
> Hmm, if that is the case, then I think narrowing the valid formats would be better. i.e. MM dd hh (enforce double digits always)

I agree. Do you want to update the timestamp pattern? E.g. to make month `MM` instead of `M`?

**Review by benedictkhoomw — APPROVED** [review]
Smoke tested with no issues. Thanks for the good work.

When you update the user guide, it might be good to specify that the earliest date accepted is 0001/01/01.

**Comment by DrWala** [comment]
@stein414 Please merge master in to resolve conflicts.

**Review by DrWala — CHANGES_REQUESTED** [review]
Please merge master in to resolve conflicts

**Review by DrWala — APPROVED** [review]

**Pull request merged**
